name: Release Builds

on:
  release:
    types: [published]

jobs:
  build:
    strategy:
      matrix:
        build_type: [linux, macos, windows]
        build_arch: [x64]
        gui: [gui, cli]
        include:
          - build_type: linux
            os: ubuntu-latest
          - build_type: macos
            os: macos-latest
          - build_type: windows
            os: windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          check-latest: true

      - name: Install dependencies
        run: pnpm install

      - name: Extract package name and version
        run: |
          echo "PACKAGE_NAME=$(node -p "require('./package.json').name")" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_ENV

      - name: Build project
        run: pnpm run build-${{ matrix.build_type }}-${{ matrix.gui }}

      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_name: multi-downloader-nx-${{ matrix.build_type }}-${{ matrix.gui }}.7z
          asset_path: ./lib/_builds/multi-downloader-nx-${{ matrix.build_type }}-${{ matrix.build_arch }}-${{ matrix.gui }}.7z
          asset_content_type: application/x-7z-compressed
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2.9.0
        with:
          context: .
          push: true
          tags: |
            multidl/multi-downloader-nx:latest
            multidl/multi-downloader-nx:${{ github.event.release.tag_name }}

